services:
  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
